---
Name: linkfield
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\LinkField\Extensions\LeftAndMainExtension
SilverStripe\Admin\Forms\UsedOnTable:
  extensions:
    - SilverStripe\LinkField\Extensions\UsedOnTableExtension
